# Generated by Django 5.1.3 on 2024-12-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_user_cart_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_id',
            field=models.IntegerField(),
        ),
    ]
